
services:
    # Node.js backend service
    syd-frontend:
        build: .
        ports:
            - '5173:5173'
        container_name: React-container
        volumes:
        - .:/usr/src/app 
        - /usr/src/app/node_modules

        
        networks:
            - frontend-network
        environment:
         API_BASE_URL: "http://localhost:8000/api"
         REACT_APP_NOMINATIM_BASE_URL: https://nominatim.openstreetmap.org/search?
         REACT_APP_MAPTILER_KEY: 
         CLOUDINARY_LINK : 
         CLOUDINARY_NAME: 
         CLOUDINARY_API_KEY: 
         CLOUDINARY_API_SECRET: 
         CLOUDINARY_PRESET: 
   
            

# Networks to allow communication between containers
networks:
    frontend-network:
        driver: bridge
