version: '3.8'

services:
    # Node.js backend service
    syd-backend:
        build: .
        ports:
            - '8000:8000'
        container_name: express-container
        volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules

        depends_on:
            - db
        networks:
            - backend-network
        environment:
            PORT: 8000
            ORIGIN_FRONTEND: http://localhost:5173
            SALT: 10
            ACCESS_SECRET: 
            REFRESH_SECRET: 
            SMTP_HOST: smtp.gmail.com
            SMTP_PORT: 465
            SMTP_SRC: false
            SMTP_MAIL: 
            SMTP_PASSWORD: 
            PG_DB_URL: 
            CLOUDINARY_NAME: 
            CLOUDINARY_APIKEY:
            CLOUDINARY_APISECRET: 
            
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER:
            POSTGRES_PASSWORD: 
            POSTGRES_DB: 
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend-network

    adminer:
        image: adminer:latest
        ports:
            - '8080:8080' # Access Adminer at http://localhost:8080
        networks:
            - backend-network

# Volumes to persist PostgreSQL data
volumes:
    postgres-data:

# Networks to allow communication between containers
networks:
    backend-network:
        driver: bridge
